export enum Currency {
    USD = 'USD',
    EUR = 'EUR',
    GBP = 'GBP',
    JPY = 'JPY',
    AUD = 'AUD',
    CAD = 'CAD',
    CHF = 'CHF',
    CNY = 'CNY',
    SEK = 'SEK',
    NZD = 'NZD',
    MXN = 'MXN',
    SGD = 'SGD',
    HKD = 'HKD',
    NOK = 'NOK',
    KRW = 'KRW',
    TRY = 'TRY',
    INR = 'INR',
    BRL = 'BRL',
    ZAR = 'ZAR',
}